# Railway YAML configuration file

version: 1.0

services:
  web:
    type: python
    command: gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    build:
      docker:
        dockerfile: Dockerfile